#!/bin/bash

pkill watch ;
pkill program ;
killall -9 prog_script_cpu_io ;

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

echo "\"AbsoluteTime\",\"Loop\",\"Phase\",\"Iteration\",\"Frequency\",\"CPU_Usage\",\"Nb_pflts\",\"IO_kbps\"" | tee $parent_path/../logs/log_frequency.csv $parent_path/../logs/log_phase.csv $parent_path/../logs/log_cpu_io.csv > /dev/null ;

true > $parent_path/../logs/result_merge.csv ;
true > $parent_path/../logs/temp_merge.csv ;

echo 3 > /proc/sys/vm/drop_caches